### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by philtay** [test-go/testify#11]
v.1.2.0 is long overdue

**Comment by dignifiedquire** [comment]
Yes, lets finish the cleanup and then cut the release. It would be great if you could start writing a changelog so people know what has changed

**Comment by hanzei** [comment]
Can we move all changes to the API to v1.3?

**Comment by philtay** [comment]
I agree. v.1.2 should just be cleaned-up post-fork release. Not sure about the requested changelog though. Can we use some tool to automate/speed-up the process? Like generating the changelog from the git commit history.

**Comment by hanzei** [comment]
There is a new release on upstream (See https://github.com/stretchr/testify/releases/tag/v1.2.0). We can close this one
